name: Data Portal Submission
description: Submit a new data portal to be added to DataPortals.org
title: Portal Submission
labels: ["portal-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Power users can fork and pull the DataPortals.org CSV data file directly:

        https://github.com/okfn/dataportals.org/blob/main/data/portals.csv

        Otherwise, follow the directions below.

  - type: markdown
    attributes:
      value: "## Key Data Portal Information"

  - type: input
    id: title
    attributes:
      label: Title
      description: Full title of the portal, e.g. "Data.Gov.UK - Official UK Government Portal"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: URL to home page of the portal
      placeholder: https://example.com
    validations:
      required: true

  - type: input
    id: manager
    attributes:
      label: Manager
      description: Name/title of the organization that set up and manages the portal
      placeholder: Organization name

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description and any additional notes about the portal, for example special licensing conditions, comments on the contents, or anything that doesn't fit in the questions below but is relevant

  - type: markdown
    attributes:
      value: "## Additional Information"

  - type: input
    id: place
    attributes:
      label: Place
      description: Short text describing the place that the portal is relate to (i.e. is supposed to cover). Should be sufficient to look it up on a map. For example, "London, UK" or "Vancouver, Canada". If no specific location just put "International"
      placeholder: e.g., London, UK or International
    validations:
      required: true

  - type: input
    id: geo_location
    attributes:
      label: Geo location
      description: If you would like the portal to show on the map, please provide latitude and longitude geographical coordinates, which can be related to the portal.
      placeholder: e.g., 51.5074, -0.1278

  - type: input
    id: country
    attributes:
      label: Country
      description: Country the portal covers. 2-digit ISO-code if possible. Note we allow regional answers if that is appropriate (e.g. EU)
      placeholder: e.g., GB, US, EU

  - type: input
    id: language
    attributes:
      label: Language
      description: The language or languages the portal is available in. Please use 2 letter ISO 639-1 codes if you can. See the list here - https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
      placeholder: e.g., en, fr, es

  - type: input
    id: license
    attributes:
      label: License
      description: Default license for the data in the data portal. You will be able to provide more information in the next question. Note "license" is used loosely to cover the general terms of use under which data is made available.
      placeholder: e.g., CC0, Open Government License

  - type: textarea
    id: license_details
    attributes:
      label: License details
      description: Provide here any additional details related to your previous answer. For example, the URL to the license on the site, or excerpts from the relevant terms of use.
      placeholder: Additional license information...

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of organization is responsible for the portal?
      options:
        - Government
        - International
        - Community
        - Research
        - Private sector
        - Third sector
        - Institutional
    validations:
      required: true

  - type: input
    id: launched
    attributes:
      label: Launched
      description: Date the portal was launched if known. If you are not sure of month and day just choose Jan 1st. Further info can go in the description. Please provide a date in ISO format - yyyy-mm-dd
      placeholder: yyyy-mm-dd

  - type: input
    id: portal_software
    attributes:
      label: Portal Software
      description: What software platform does the portal use
      placeholder: e.g., CKAN, Socrata, Custom

  - type: textarea
    id: portal_software_details
    attributes:
      label: Portal Software details
      description: If you answered 'Other' or 'Custom/in-house' implementation to the question above, please feel free to give more details here. If there is a platform we've missed, we'll add it to the list.
      placeholder: Additional software details...

  - type: dropdown
    id: api_type
    attributes:
      label: API Type
      description: Does the portal have any kind of API (structured metadata about the data that can be downloaded)? If multiple options apply, please choose the most extensive/advanced API.
      options:
        - Basic
        - REST API
        - GraphQL
        - SPARQL
        - Other

  - type: input
    id: api_endpoint
    attributes:
      label: API Endpoint
      description: URL for accessing the API
      placeholder: https://api.example.com

  - type: input
    id: full_metadata_download
    attributes:
      label: Full metadata download
      description: URL to download entire portal contents, either via an API, or dump provided by the publisher or a 3rd party
      placeholder: https://example.com/metadata-dump

  - type: markdown
    attributes:
      value: "## Your Information"

  - type: input
    id: your_name
    attributes:
      label: Your Name
      description: So we know who is submitting this and can credit you as appropriate.
      placeholder: Your name

  - type: input
    id: your_link
    attributes:
      label: Your Link
      description: A link we could use if we need to credit you
      placeholder: https://example.com/your-profile

  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Use
      description: By submitting material in this issue you agree to
      options:
        - label: The terms of use - https://okfn.org/terms-of-use/
          required: true
        - label: To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - https://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - https://opendatacommons.org/licenses/pddl/1.0/). This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - https://opendefinition.org/od/.
          required: true
